# 调试

## 宏

PyO3 的属性（`#[pyclass]`、`#[pymodule]` 等）是 [过程宏](https://doc.rust-lang.org/reference/procedural-macros.html)，这意味着它们会重写被注解项的源代码。你可以使用以下命令查看生成的源代码，同时展开其他一些内容：

```bash
cargo rustc --profile=check -- -Z unstable-options --pretty=expanded > expanded.rs; rustfmt expanded.rs
```

（如果你还没有安装 [rustfmt](https://github.com/rust-lang-nursery/rustfmt)，你可能需要先安装它。）

你还可以通过添加 `-Z trace-macros` 来调试经典的 `!` 宏：

```bash
cargo rustc --profile=check -- -Z unstable-options --pretty=expanded -Z trace-macros > expanded.rs; rustfmt expanded.rs
```

请注意，这些命令需要使用 Rust 的夜间版本，并且可能偶尔会有错误。有关这些命令的更详细和稳定的版本，请参见 [cargo expand](https://github.com/dtolnay/cargo-expand)。

## 使用 Valgrind 运行

Valgrind 是一个检测内存管理错误（如内存泄漏）的工具。

你首先需要安装 Python 的调试版本，否则 Valgrind 不会产生可用的结果。在 Ubuntu 中，例如有一个 `python3-dbg` 包。

激活一个带有调试解释器的环境并重新编译。如果你在 Linux 上，使用 `ldd` 和你的二进制文件名检查你链接的是 `libpython3.7d.so.1.0` 而不是 `libpython3.7.so.1.0`。

[下载 CPython 的抑制文件](https://raw.githubusercontent.com/python/cpython/master/Misc/valgrind-python.supp)。

使用 `valgrind --suppressions=valgrind-python.supp ./my-command --with-options` 运行 Valgrind。

## 获取堆栈跟踪

调查崩溃（如段错误）的最佳起点是回溯。你可以将 `RUST_BACKTRACE=1` 设置为环境变量，以在 `panic!` 时获取堆栈跟踪。或者，你可以使用调试器，如 `gdb`，来探索问题。Rust 提供了一个包装器 `rust-gdb`，它具有用于检查 Rust 变量的美化打印功能。由于 PyO3 使用 `cdylib` 作为 Python 共享对象，因此它不会在 `rust-gdb` 中接收美化打印调试钩子（[rust-lang/rust#96365](https://github.com/rust-lang/rust/issues/96365)）。提到的问题包含了在这种情况下启用美化打印的解决方法。

 * 按照前一章的描述链接到 Python 的调试版本
 * 运行 `rust-gdb <my-binary>`
 * 如果你正在调查 `panic!`，在 `rust_panic` 上设置一个断点（`b`）
 * 输入 `r` 以运行
 * 崩溃发生后，输入 `bt` 或 `bt full` 打印堆栈跟踪

通常，运行一小段 Python 代码以测试 Rust 的某个部分是很有帮助的。

```console
rust-gdb --args python -c "import my_package; my_package.sum_to_string(1, 2)"
```